# Generated by Django 2.1 on 2018-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField(choices=[('ISE', 'Information Science Engg.'), ('CSE', 'Computer Science Engg.')], max_length=3)),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], help_text='Year of joining college')),
                ('section', models.CharField(choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section'), ('D', 'D Section')], max_length=1)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.AlterUniqueTogether(
            name='batchmodel',
            unique_together={('department', 'year', 'section')},
        ),
    ]
