# Generated by Django 2.1 on 2018-09-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_auto_20180908_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchmodel',
            options={'ordering': ['department', 'year', 'section'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
