# Generated by Django 2.0.5 on 2018-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='class representative'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='administrator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], help_text='Year which you joined the college.', null=True, verbose_name='Year'),
        ),
    ]
