# Generated by Django 2.0.5 on 2018-07-19 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180718_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='usn_err', message='Please enter valid USN.(must be in capital letter)', regex='^1BM\\d{2}[A-Z]{2,3}\\d{3}$')]),
        ),
    ]
