# Generated by Django 2.0.5 on 2018-07-20 11:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_batch-dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(default='profile_pics/default/default.jpg', upload_to=accounts.models.upload_image_path),
        ),
    ]
