# Generated by Django 2.0.5 on 2018-07-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_default_img'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('pub_date',), 'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
        migrations.AddField(
            model_name='votedata',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.AddField(
            model_name='votedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='poll',
            name='voter',
            field=models.ManyToManyField(related_name='poll', through='polls.VoteData', to='accounts.Student'),
        ),
    ]
